// Selected from the 1 October 2026 daily-departures list; one ICAO operator per row.
// https://www.flightsfrom.com/top-100-airlines
// Prefixes verified against the FAA directory; see README for selection details.
// https://www.faa.gov/air_traffic/publications/atpubs/cnt_html/chap3_section_3.html
export const airlines = [
  { id: 'american-airlines', name: 'American Airlines', prefix: 'AAL' },
  { id: 'united-airlines', name: 'United Airlines', prefix: 'UAL' },
  { id: 'delta-air-lines', name: 'Delta Air Lines', prefix: 'DAL' },
  { id: 'southwest-airlines', name: 'Southwest Airlines', prefix: 'SWA' },
  { id: 'ryanair', name: 'Ryanair', prefix: 'RYR' },
  { id: 'china-eastern-airlines', name: 'China Eastern Airlines', prefix: 'CES' },
  { id: 'indigo', name: 'IndiGo', prefix: 'IGO' },
  { id: 'china-southern-airlines', name: 'China Southern Airlines', prefix: 'CSN' },
  { id: 'easyjet-uk', name: 'easyJet UK', prefix: 'EZY' },
  { id: 'air-china', name: 'Air China', prefix: 'CCA' },
  { id: 'alaska-airlines', name: 'Alaska Airlines', prefix: 'ASA' },
  { id: 'air-canada', name: 'Air Canada', prefix: 'ACA' },
  { id: 'turkish-airlines', name: 'Turkish Airlines', prefix: 'THY' },
  { id: 'latam-airlines-chile', name: 'LATAM Airlines Chile', prefix: 'LAN' },
  { id: 'lufthansa', name: 'Lufthansa', prefix: 'DLH' },
  { id: 'japan-airlines', name: 'Japan Airlines', prefix: 'JAL' },
  { id: 'all-nippon-airways', name: 'All Nippon Airways', prefix: 'ANA' },
  { id: 'qantas', name: 'Qantas', prefix: 'QFA' },
  { id: 'azul', name: 'Azul', prefix: 'AZU' },
  { id: 'aeroflot', name: 'Aeroflot', prefix: 'AFL' },
  { id: 'shenzhen-airlines', name: 'Shenzhen Airlines', prefix: 'CSZ' },
  { id: 'british-airways', name: 'British Airways', prefix: 'BAW' },
  { id: 'hainan-airlines', name: 'Hainan Airlines', prefix: 'CHH' },
  { id: 'klm', name: 'KLM Royal Dutch Airlines', prefix: 'KLM' },
  { id: 'avianca-colombia', name: 'Avianca Colombia', prefix: 'AVA' },
  { id: 'jetblue-airways', name: 'JetBlue Airways', prefix: 'JBU' },
  { id: 'pegasus-airlines', name: 'Pegasus Airlines', prefix: 'PGT' },
  { id: 'air-india', name: 'Air India', prefix: 'AIC' },
  { id: 'iberia', name: 'Iberia', prefix: 'IBE' },
  { id: 'sichuan-airlines', name: 'Sichuan Airlines', prefix: 'CSC' },
  { id: 'shandong-airlines', name: 'Shandong Airlines', prefix: 'CDG' },
  { id: 'spring-airlines', name: 'Spring Airlines', prefix: 'CQH' },
  { id: 'air-france', name: 'Air France', prefix: 'AFR' },
  { id: 'wizz-air-hungary', name: 'Wizz Air Hungary', prefix: 'WZZ' },
  { id: 'xiamen-airlines', name: 'Xiamen Airlines', prefix: 'CXA' },
  { id: 'wizz-air-malta', name: 'Wizz Air Malta', prefix: 'WMT' },
  { id: 'scandinavian-airlines', name: 'Scandinavian Airlines', prefix: 'SAS' },
  { id: 'vueling', name: 'Vueling', prefix: 'VLG' },
  { id: 'volaris', name: 'Volaris', prefix: 'VOI' },
  { id: 'emirates', name: 'Emirates', prefix: 'UAE' },
  { id: 'eurowings', name: 'Eurowings', prefix: 'EWG' },
  { id: 'ethiopian-airlines', name: 'Ethiopian Airlines', prefix: 'ETH' },
  { id: 'china-express-airlines', name: 'China Express Airlines', prefix: 'HXA' },
  { id: 'aeromexico', name: 'Aeromexico', prefix: 'AMX' },
  { id: 'qatar-airways', name: 'Qatar Airways', prefix: 'QTR' },
  { id: 'airasia-malaysia', name: 'AirAsia Malaysia', prefix: 'AXM' },
  { id: 'westjet', name: 'WestJet', prefix: 'WJA' },
  { id: 'frontier-airlines', name: 'Frontier Airlines', prefix: 'FFT' },
  { id: 'air-india-express', name: 'Air India Express', prefix: 'AXB' },
  { id: 'air-new-zealand', name: 'Air New Zealand', prefix: 'ANZ' },
  { id: 'jet2-com', name: 'Jet2.com', prefix: 'EXS' },
  { id: 'saudia', name: 'Saudia', prefix: 'SVA' },
  { id: 'gol', name: 'GOL', prefix: 'GLO' },
  { id: 'jetstar-airways', name: 'Jetstar Airways', prefix: 'JST' },
  { id: 'viva-aerobus', name: 'Viva Aerobus', prefix: 'VIV' },
  { id: 'copa-airlines', name: 'Copa Airlines', prefix: 'CMP' },
  { id: 'korean-air', name: 'Korean Air', prefix: 'KAL' },
  { id: 'lion-air', name: 'Lion Air', prefix: 'LNI' },
  { id: 'singapore-airlines', name: 'Singapore Airlines', prefix: 'SIA' },
  { id: 'chengdu-airlines', name: 'Chengdu Airlines', prefix: 'UEA' },
  { id: 'ajet', name: 'AJet', prefix: 'TKJ' },
  { id: 'wideroe', name: 'Widerøe', prefix: 'WIF' },
  { id: 'austrian-airlines', name: 'Austrian Airlines', prefix: 'AUA' },
  { id: 'aer-lingus', name: 'Aer Lingus', prefix: 'EIN' },
  { id: 'vietnam-airlines', name: 'Vietnam Airlines', prefix: 'HVN' },
  { id: 'vietjet-air', name: 'VietJet Air', prefix: 'VJC' },
  { id: 'shanghai-airlines', name: 'Shanghai Airlines', prefix: 'CSH' },
  { id: 'cathay-pacific', name: 'Cathay Pacific', prefix: 'CPA' },
  { id: 'swiss', name: 'SWISS', prefix: 'SWR' },
  { id: 'transavia-france', name: 'Transavia France', prefix: 'TVF' },
  { id: 'loong-air', name: 'Loong Air', prefix: 'CDC' },
  { id: 'thai-airasia', name: 'Thai AirAsia', prefix: 'AIQ' },
  { id: 'batik-air-indonesia', name: 'Batik Air Indonesia', prefix: 'BTK' },
  { id: 'juneyao-airlines', name: 'Juneyao Airlines', prefix: 'DKH' },
  { id: 'aegean-airlines', name: 'Aegean Airlines', prefix: 'AEE' },
  { id: 'etihad-airways', name: 'Etihad Airways', prefix: 'ETD' },
  { id: 'flydubai', name: 'flydubai', prefix: 'FDB' },
  { id: 'tianjin-airlines', name: 'Tianjin Airlines', prefix: 'GCR' },
  { id: 'finnair', name: 'Finnair', prefix: 'FIN' },
  { id: 'cebu-pacific', name: 'Cebu Pacific', prefix: 'CEB' },
  { id: 'virgin-australia', name: 'Virgin Australia', prefix: 'VOZ' },
  { id: 'flynas', name: 'Flynas', prefix: 'KNE' },
  { id: 'cape-air', name: 'Cape Air', prefix: 'KAP' },
  { id: 's7-airlines', name: 'S7 Airlines', prefix: 'SBI' },
  { id: 'breeze-airways', name: 'Breeze Airways', prefix: 'MXY' },
  { id: 'porter-airlines', name: 'Porter Airlines', prefix: 'POE' },
  { id: 'sunexpress', name: 'SunExpress', prefix: 'SXS' },
  { id: 'citilink', name: 'Citilink', prefix: 'CTV' },
  { id: 'super-air-jet', name: 'Super Air Jet', prefix: 'SJV' },
  { id: 'malaysia-airlines', name: 'Malaysia Airlines', prefix: 'MAS' },
  { id: 'philippine-airlines', name: 'Philippine Airlines', prefix: 'PAL' },
  { id: 'airlink', name: 'Airlink', prefix: 'LNK' },
  { id: 'binter-canarias', name: 'Binter Canarias', prefix: 'IBB' },
  { id: 'thai-airways-international', name: 'Thai Airways International', prefix: 'THA' },
  { id: 'norwegian-air-sweden', name: 'Norwegian Air Sweden', prefix: 'NSZ' },
  { id: 'condor', name: 'Condor', prefix: 'CFG' },
  { id: 'garuda-indonesia', name: 'Garuda Indonesia', prefix: 'GIA' },
  { id: 'beijing-capital-airlines', name: 'Beijing Capital Airlines', prefix: 'CBJ' },
  { id: 'air-arabia', name: 'Air Arabia', prefix: 'ABY' },
  { id: 'jeju-air', name: 'Jeju Air', prefix: 'JJA' },
];
